14 sprint #1
Galyk-Ilya/java-shareit pull request #2
Opened 2023-07-22 07:56 UTC by Galyk-Ilya

2023-07-22 15:15 UTC, kalitva requested changes

2023-07-22 15:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/bookingRepository/BookingRepository.java
> +}
Вместо определения всех этих методов для фильтрации объектов можно воспользоваться `Specification`, попробуй, это используется почти везде, где есть spring data

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2023-07-22 15:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private final BookingServiceImpl bookingServiceImpl;
`BookingServiceImpl --> BookingService`

Храни сервисы по типу интерфейса

2023-07-22 15:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                  @RequestParam(defaultValue = "ALL", required = false) String state) {
Наличие значения `defaultValue` автоматически неявно устанавливает `required = false`

2023-07-22 15:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +@Data
Давай лучше вместо `@Data` использовать 

```
@Getter
@Setter
```

2023-07-22 15:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +import javax.persistence.*;
Не используй wildcard импорты.

https://google.github.io/styleguide/javaguide.html#s3.3.1-wildcard-imports

Это может служить причиной лишних конфликтов при мерже веток. Настрой intellij чтобы она не схлопывала импорты

2023-07-22 15:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new NotFoundException("Владелец не может забронировать свою вещь");
Сообщения в исключениях только по английски, иначе есть вероятность, что в логах получишь подобный текст - `???? ??? ??????? ????`

2023-07-22 15:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +    List<Comment> findAllByItemId(long itemId);
`findAllByItemId --> findByItemId`

`All` обычно не пишут

2023-07-22 15:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text.isEmpty())
Всегда оборачивай тело условий и циклов в фигурные скобки, даже для одного стэйтмента

https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2023-07-22 15:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
>      }
В последних двух методах возможно лучше подойдут методы `Stream#takeWhile` и `Stream#dropWhile`

2023-07-22 15:15 UTC, kalitva commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS users, items, bookings, comments CASCADE;
Не думаю, что дропать базы при каждом запуске - хорошая идея. H2 хранить данные в памяти, так что для ее очистки достаточно просто перезапустить приложение

Кстати, можешь попробовать использовать `spring-boot-dev-tools`, приложение будет перезапускаться автоматически при каждом изменении

2023-07-23 12:28 UTC, Galyk-Ilya commented on src/main/java/ru/practicum/shareit/booking/bookingRepository/BookingRepository.java
> +}
Сходу не вник, постараюсь поправить позже, как раскидаюсь по дедлайнам)
Если ты не против

2023-07-23 13:11 UTC, Galyk-Ilya commented
Замечания исправил, буду рад если прожмешь, чтобы открылось следующее тз, при этом продолжу исправлять все что пропишем дальше

2023-07-23 17:57 UTC, kalitva approved these changes

2023-07-23 17:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/bookingRepository/BookingRepository.java
> +}
Окей

2023-07-23 17:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private final BookingService bookingServiceImpl;
`bookingServiceImpl --> bookingService`

2023-07-23 17:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +        log.info("Error 400: {}", e.getMessage());
Больше подходит уровень WARN или ERROR

2023-07-23 17:57 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public CommentDto createComment(@RequestHeader("X-Sharer-User-Id") long userId,
Давай вынесем `X-Sharer-User-Id` в константу

2023-09-08 05:53 UTC, merged